#!/usr/bin/env node
// Generate exact SVG outlines for the 12 Tamil vowels from the real font glyph,
// normalized into a 0 0 200 200 box. Run on macOS:  node tools/gen-trace.mjs
// Requires: npm i fontkit   (uses the system "Tamil Sangam MN" .ttc collection)

import * as fontkit from "fontkit";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FONT = "/System/Library/Fonts/Supplemental/Tamil Sangam MN.ttc";
const VOWELS = ["அ", "ஆ", "இ", "ஈ", "உ", "ஊ", "எ", "ஏ", "ஐ", "ஒ", "ஓ", "ஔ"];

const BOX = 200, PAD = 22; // target viewBox + padding

function pickFont() {
  const f = fontkit.openSync(FONT);
  if (f.type === "TTC" || f.fonts) {
    return (f.fonts || []).find((x) => /Tamil Sangam/i.test(x.familyName || x.fullName || "")) || f.fonts[0];
  }
  return f;
}

const font = pickFont();
const TRACE = {};

for (const ch of VOWELS) {
  const glyph = font.glyphForCodePoint(ch.codePointAt(0));
  const bb = glyph.path.bbox; // { minX, minY, maxX, maxY } in font units (y-up)
  const w = bb.maxX - bb.minX, h = bb.maxY - bb.minY;
  const s = (BOX - 2 * PAD) / Math.max(w, h);
  // flip Y (font y-up -> SVG y-down) + scale to fit (fontkit transforms return NEW paths)
  let p = glyph.path.scale(s, -s);
  const b2 = p.bbox;
  const dx = (BOX - (b2.maxX - b2.minX)) / 2 - b2.minX;
  const dy = (BOX - (b2.maxY - b2.minY)) / 2 - b2.minY;
  p = p.translate(dx, dy);
  TRACE[ch] = p.toSVG();
}

const out = "// Generated by tools/gen-trace.mjs — exact glyph outlines (Tamil Sangam MN), 0 0 200 200.\n" +
  "const TRACE = " + JSON.stringify(TRACE, null, 2) + ";\n";
writeFileSync(join(ROOT, "trace-paths.js"), out);
console.log(`Wrote trace-paths.js with ${Object.keys(TRACE).length} vowel outlines.`);
